name: Django Tests

on:
  push:
    branches:
      - master
      - main
  pull_request:

env:
  DATAPORTEN_ID: ${{ secrets.DATAPORTEN_ID }}
  DATAPORTEN_REDIRECT_URI: ${{ secrets.DATAPORTEN_REDIRECT_URI }}
  DATAPORTEN_SECRET: ${{ secrets.DATAPORTEN_SECRET }}
  GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

jobs:
  test:
    name: API tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the project
        run: |
          docker-compose -f docker-compose.test.yml up -d

      - name: Run the django tests
        run: |
          docker-compose exec -T backend coverage run manage.py test
          docker-compose exec -T backend coverage xml

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: backend/coverage.xml
          flags: apitests # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
